; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

; Velocità del monitor seriale (fondamentale per leggere i dati sul PC)
monitor_speed = 115200

; Librerie da scaricare automaticamente perchè non sono già fornite dal framework Arduino
lib_deps =
    jgromes/RadioLib     ; per gestire il modulo LoRa
    olikraus/U8g2    ; per gestire il display OLED
    mikalhart/TinyGPSPlus @ ^1.0.3

; Build Flags: Diciamo al codice che stiamo usando una Heltec V3 
; e attiviamo i pin interni corretti
build_flags =
    -D REGION_EU868
    -D HELTEC_V3